version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn-install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
  test:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: test
          command: yarn run test:libs
  publish:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - add_ssh_keys:
          finterprints:
            - "86:ff:fc:16:73:4d:f9:12:31:bd:d7:6b:ac:eb:d5:e2"
      - run:
          name: Logging in to private npm registry
          command: |
            npm set registry https://registry.npmjs.org
            echo //registry.npmjs.org/:_authToken=\"${NPM_TOKEN}\" >> ~/.npmrc
      - run:
          name: Configuring git
          command: |
            git config --global user.email "${git log -1 --pretty=format:'%ae'}"
            git config --global user.name "${git log -1 --pretty=format:'%an'}"
      - run:
          name: npm-publish
          command: yarn run publish:libs
workflows:
  version: 2
  run-tests:
    jobs:
      - build
      - test:
          requires:
            - build
  run-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
